// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zrchain/zenbtc/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	EthBatcherAddr      string   `protobuf:"bytes,1,opt,name=ethBatcherAddr,proto3" json:"ethBatcherAddr,omitempty"`
	DepositKeyringAddr  string   `protobuf:"bytes,2,opt,name=depositKeyringAddr,proto3" json:"depositKeyringAddr,omitempty"`
	MinterKeyID         uint64   `protobuf:"varint,3,opt,name=minterKeyID,proto3" json:"minterKeyID,omitempty"`
	WithdrawerKeyID     uint64   `protobuf:"varint,4,opt,name=withdrawerKeyID,proto3" json:"withdrawerKeyID,omitempty"`
	UnstakerKeyID       uint64   `protobuf:"varint,5,opt,name=unstakerKeyID,proto3" json:"unstakerKeyID,omitempty"`
	RewardsDepositKeyID uint64   `protobuf:"varint,6,opt,name=rewardsDepositKeyID,proto3" json:"rewardsDepositKeyID,omitempty"`
	ChangeAddressKeyIDs []uint64 `protobuf:"varint,7,rep,packed,name=changeAddressKeyIDs,proto3" json:"changeAddressKeyIDs,omitempty"`
	BitcoinProxyAddress string   `protobuf:"bytes,8,opt,name=bitcoinProxyAddress,proto3" json:"bitcoinProxyAddress,omitempty"`
	Authority           string   `protobuf:"bytes,9,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_53cfc222fdb324be, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEthBatcherAddr() string {
	if m != nil {
		return m.EthBatcherAddr
	}
	return ""
}

func (m *Params) GetDepositKeyringAddr() string {
	if m != nil {
		return m.DepositKeyringAddr
	}
	return ""
}

func (m *Params) GetMinterKeyID() uint64 {
	if m != nil {
		return m.MinterKeyID
	}
	return 0
}

func (m *Params) GetWithdrawerKeyID() uint64 {
	if m != nil {
		return m.WithdrawerKeyID
	}
	return 0
}

func (m *Params) GetUnstakerKeyID() uint64 {
	if m != nil {
		return m.UnstakerKeyID
	}
	return 0
}

func (m *Params) GetRewardsDepositKeyID() uint64 {
	if m != nil {
		return m.RewardsDepositKeyID
	}
	return 0
}

func (m *Params) GetChangeAddressKeyIDs() []uint64 {
	if m != nil {
		return m.ChangeAddressKeyIDs
	}
	return nil
}

func (m *Params) GetBitcoinProxyAddress() string {
	if m != nil {
		return m.BitcoinProxyAddress
	}
	return ""
}

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "zrchain.zenbtc.Params")
}

func init() { proto.RegisterFile("zrchain/zenbtc/params.proto", fileDescriptor_53cfc222fdb324be) }

var fileDescriptor_53cfc222fdb324be = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xeb, 0x40,
	0x18, 0x85, 0x9b, 0xdb, 0xde, 0xde, 0xdb, 0x11, 0x2b, 0x8e, 0x82, 0xa1, 0x4a, 0x0c, 0x22, 0x52,
	0x44, 0x12, 0xc1, 0x9d, 0x3b, 0x4b, 0x11, 0x4a, 0x37, 0xa5, 0x4b, 0x77, 0x93, 0xc9, 0x90, 0x19,
	0x6a, 0x66, 0xc2, 0xcc, 0x94, 0x36, 0x7d, 0x04, 0x57, 0x3e, 0x82, 0x4b, 0x97, 0x3e, 0x86, 0xcb,
	0x2e, 0x5d, 0x4a, 0xbb, 0xd0, 0xc7, 0x90, 0x4c, 0x9a, 0xaa, 0x25, 0x9b, 0xe1, 0xe7, 0x9c, 0xef,
	0xfc, 0xfc, 0xcc, 0x01, 0x87, 0x33, 0x89, 0x29, 0x62, 0xdc, 0x9f, 0x11, 0x1e, 0x68, 0xec, 0x27,
	0x48, 0xa2, 0x58, 0x79, 0x89, 0x14, 0x5a, 0xc0, 0xe6, 0xca, 0xf4, 0x72, 0xb3, 0xb5, 0x8b, 0x62,
	0xc6, 0x85, 0x6f, 0xde, 0x1c, 0x69, 0xed, 0x47, 0x22, 0x12, 0x66, 0xf4, 0xb3, 0x29, 0x57, 0x4f,
	0x9e, 0xab, 0xa0, 0x3e, 0x30, 0x9b, 0xe0, 0x19, 0x68, 0x12, 0x4d, 0x3b, 0x48, 0x63, 0x4a, 0xe4,
	0x4d, 0x18, 0x4a, 0xdb, 0x72, 0xad, 0x76, 0x63, 0xb8, 0xa1, 0x42, 0x0f, 0xc0, 0x90, 0x24, 0x42,
	0x31, 0xdd, 0x27, 0xa9, 0x64, 0x3c, 0x32, 0xec, 0x1f, 0xc3, 0x96, 0x38, 0xd0, 0x05, 0x5b, 0x31,
	0xe3, 0x9a, 0xc8, 0x3e, 0x49, 0x7b, 0x5d, 0xbb, 0xea, 0x5a, 0xed, 0xda, 0xf0, 0xa7, 0x04, 0xdb,
	0x60, 0x67, 0xc2, 0x34, 0x0d, 0x25, 0x9a, 0x14, 0x54, 0xcd, 0x50, 0x9b, 0x32, 0x3c, 0x05, 0xdb,
	0x63, 0xae, 0x34, 0x1a, 0x15, 0xdc, 0x5f, 0xc3, 0xfd, 0x16, 0xe1, 0x25, 0xd8, 0x93, 0x64, 0x82,
	0x64, 0xa8, 0xba, 0xeb, 0x73, 0x7a, 0x5d, 0xbb, 0x6e, 0xd8, 0x32, 0x2b, 0x4b, 0x60, 0x8a, 0x78,
	0x44, 0xb2, 0x8b, 0x89, 0x52, 0x46, 0x55, 0xf6, 0x3f, 0xb7, 0x9a, 0x25, 0x4a, 0xac, 0x2c, 0x11,
	0x30, 0x8d, 0x05, 0xe3, 0x03, 0x29, 0xa6, 0xe9, 0xca, 0xb4, 0xff, 0x9b, 0x6f, 0x28, 0xb3, 0xe0,
	0x11, 0x68, 0xa0, 0xb1, 0xa6, 0x42, 0x32, 0x9d, 0xda, 0x0d, 0xc3, 0x7d, 0x0b, 0xd7, 0xee, 0xe7,
	0xd3, 0xb1, 0xf5, 0xf0, 0xf1, 0x72, 0x7e, 0x50, 0xf4, 0x3c, 0x2d, 0x9a, 0xce, 0xfb, 0xe9, 0xdc,
	0xbe, 0x2e, 0x1c, 0x6b, 0xbe, 0x70, 0xac, 0xf7, 0x85, 0x63, 0x3d, 0x2e, 0x9d, 0xca, 0x7c, 0xe9,
	0x54, 0xde, 0x96, 0x4e, 0xe5, 0xee, 0x22, 0x62, 0x9a, 0x8e, 0x03, 0x0f, 0x8b, 0x38, 0xcb, 0x48,
	0x81, 0x47, 0xf7, 0x28, 0x50, 0x45, 0x7e, 0xbd, 0x48, 0xa7, 0x09, 0x51, 0x41, 0xdd, 0x34, 0x7f,
	0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0x21, 0xf4, 0x79, 0x4a, 0x51, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EthBatcherAddr != that1.EthBatcherAddr {
		return false
	}
	if this.DepositKeyringAddr != that1.DepositKeyringAddr {
		return false
	}
	if this.MinterKeyID != that1.MinterKeyID {
		return false
	}
	if this.WithdrawerKeyID != that1.WithdrawerKeyID {
		return false
	}
	if this.UnstakerKeyID != that1.UnstakerKeyID {
		return false
	}
	if this.RewardsDepositKeyID != that1.RewardsDepositKeyID {
		return false
	}
	if len(this.ChangeAddressKeyIDs) != len(that1.ChangeAddressKeyIDs) {
		return false
	}
	for i := range this.ChangeAddressKeyIDs {
		if this.ChangeAddressKeyIDs[i] != that1.ChangeAddressKeyIDs[i] {
			return false
		}
	}
	if this.BitcoinProxyAddress != that1.BitcoinProxyAddress {
		return false
	}
	if this.Authority != that1.Authority {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.BitcoinProxyAddress) > 0 {
		i -= len(m.BitcoinProxyAddress)
		copy(dAtA[i:], m.BitcoinProxyAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BitcoinProxyAddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ChangeAddressKeyIDs) > 0 {
		dAtA2 := make([]byte, len(m.ChangeAddressKeyIDs)*10)
		var j1 int
		for _, num := range m.ChangeAddressKeyIDs {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintParams(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x3a
	}
	if m.RewardsDepositKeyID != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RewardsDepositKeyID))
		i--
		dAtA[i] = 0x30
	}
	if m.UnstakerKeyID != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UnstakerKeyID))
		i--
		dAtA[i] = 0x28
	}
	if m.WithdrawerKeyID != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WithdrawerKeyID))
		i--
		dAtA[i] = 0x20
	}
	if m.MinterKeyID != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinterKeyID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DepositKeyringAddr) > 0 {
		i -= len(m.DepositKeyringAddr)
		copy(dAtA[i:], m.DepositKeyringAddr)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DepositKeyringAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EthBatcherAddr) > 0 {
		i -= len(m.EthBatcherAddr)
		copy(dAtA[i:], m.EthBatcherAddr)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EthBatcherAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EthBatcherAddr)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DepositKeyringAddr)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MinterKeyID != 0 {
		n += 1 + sovParams(uint64(m.MinterKeyID))
	}
	if m.WithdrawerKeyID != 0 {
		n += 1 + sovParams(uint64(m.WithdrawerKeyID))
	}
	if m.UnstakerKeyID != 0 {
		n += 1 + sovParams(uint64(m.UnstakerKeyID))
	}
	if m.RewardsDepositKeyID != 0 {
		n += 1 + sovParams(uint64(m.RewardsDepositKeyID))
	}
	if len(m.ChangeAddressKeyIDs) > 0 {
		l = 0
		for _, e := range m.ChangeAddressKeyIDs {
			l += sovParams(uint64(e))
		}
		n += 1 + sovParams(uint64(l)) + l
	}
	l = len(m.BitcoinProxyAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthBatcherAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthBatcherAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositKeyringAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositKeyringAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinterKeyID", wireType)
			}
			m.MinterKeyID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinterKeyID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawerKeyID", wireType)
			}
			m.WithdrawerKeyID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawerKeyID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnstakerKeyID", wireType)
			}
			m.UnstakerKeyID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnstakerKeyID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsDepositKeyID", wireType)
			}
			m.RewardsDepositKeyID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardsDepositKeyID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ChangeAddressKeyIDs = append(m.ChangeAddressKeyIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParams
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParams
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ChangeAddressKeyIDs) == 0 {
					m.ChangeAddressKeyIDs = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ChangeAddressKeyIDs = append(m.ChangeAddressKeyIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeAddressKeyIDs", wireType)
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BitcoinProxyAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BitcoinProxyAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
