// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zrchain/zenbtc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryLockTransactionsRequest struct {
}

func (m *QueryLockTransactionsRequest) Reset()         { *m = QueryLockTransactionsRequest{} }
func (m *QueryLockTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLockTransactionsRequest) ProtoMessage()    {}
func (*QueryLockTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{2}
}
func (m *QueryLockTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockTransactionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockTransactionsRequest.Merge(m, src)
}
func (m *QueryLockTransactionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockTransactionsRequest proto.InternalMessageInfo

type QueryLockTransactionsResponse struct {
	LockTransactions []*LockTransaction `protobuf:"bytes,1,rep,name=lock_transactions,json=lockTransactions,proto3" json:"lock_transactions,omitempty"`
}

func (m *QueryLockTransactionsResponse) Reset()         { *m = QueryLockTransactionsResponse{} }
func (m *QueryLockTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLockTransactionsResponse) ProtoMessage()    {}
func (*QueryLockTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{3}
}
func (m *QueryLockTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockTransactionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockTransactionsResponse.Merge(m, src)
}
func (m *QueryLockTransactionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockTransactionsResponse proto.InternalMessageInfo

func (m *QueryLockTransactionsResponse) GetLockTransactions() []*LockTransaction {
	if m != nil {
		return m.LockTransactions
	}
	return nil
}

type QueryRedemptionsRequest struct {
	StartIndex uint64           `protobuf:"varint,1,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	Status     RedemptionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=zrchain.zenbtc.RedemptionStatus" json:"status,omitempty"`
}

func (m *QueryRedemptionsRequest) Reset()         { *m = QueryRedemptionsRequest{} }
func (m *QueryRedemptionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRedemptionsRequest) ProtoMessage()    {}
func (*QueryRedemptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{4}
}
func (m *QueryRedemptionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRedemptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRedemptionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRedemptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRedemptionsRequest.Merge(m, src)
}
func (m *QueryRedemptionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRedemptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRedemptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRedemptionsRequest proto.InternalMessageInfo

func (m *QueryRedemptionsRequest) GetStartIndex() uint64 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

func (m *QueryRedemptionsRequest) GetStatus() RedemptionStatus {
	if m != nil {
		return m.Status
	}
	return RedemptionStatus_UNSPECIFIED
}

type QueryRedemptionsResponse struct {
	Redemptions []Redemption `protobuf:"bytes,1,rep,name=redemptions,proto3" json:"redemptions"`
}

func (m *QueryRedemptionsResponse) Reset()         { *m = QueryRedemptionsResponse{} }
func (m *QueryRedemptionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRedemptionsResponse) ProtoMessage()    {}
func (*QueryRedemptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{5}
}
func (m *QueryRedemptionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRedemptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRedemptionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRedemptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRedemptionsResponse.Merge(m, src)
}
func (m *QueryRedemptionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRedemptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRedemptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRedemptionsResponse proto.InternalMessageInfo

func (m *QueryRedemptionsResponse) GetRedemptions() []Redemption {
	if m != nil {
		return m.Redemptions
	}
	return nil
}

type QueryPendingMintTransactionsRequest struct {
}

func (m *QueryPendingMintTransactionsRequest) Reset()         { *m = QueryPendingMintTransactionsRequest{} }
func (m *QueryPendingMintTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingMintTransactionsRequest) ProtoMessage()    {}
func (*QueryPendingMintTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{6}
}
func (m *QueryPendingMintTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingMintTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingMintTransactionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingMintTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingMintTransactionsRequest.Merge(m, src)
}
func (m *QueryPendingMintTransactionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingMintTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingMintTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingMintTransactionsRequest proto.InternalMessageInfo

type QueryPendingMintTransactionsResponse struct {
	PendingMintTransactions []*PendingMintTransaction `protobuf:"bytes,1,rep,name=pending_mint_transactions,json=pendingMintTransactions,proto3" json:"pending_mint_transactions,omitempty"`
}

func (m *QueryPendingMintTransactionsResponse) Reset()         { *m = QueryPendingMintTransactionsResponse{} }
func (m *QueryPendingMintTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingMintTransactionsResponse) ProtoMessage()    {}
func (*QueryPendingMintTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{7}
}
func (m *QueryPendingMintTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingMintTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingMintTransactionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingMintTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingMintTransactionsResponse.Merge(m, src)
}
func (m *QueryPendingMintTransactionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingMintTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingMintTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingMintTransactionsResponse proto.InternalMessageInfo

func (m *QueryPendingMintTransactionsResponse) GetPendingMintTransactions() []*PendingMintTransaction {
	if m != nil {
		return m.PendingMintTransactions
	}
	return nil
}

type QuerySupplyRequest struct {
}

func (m *QuerySupplyRequest) Reset()         { *m = QuerySupplyRequest{} }
func (m *QuerySupplyRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySupplyRequest) ProtoMessage()    {}
func (*QuerySupplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{8}
}
func (m *QuerySupplyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySupplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySupplyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySupplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupplyRequest.Merge(m, src)
}
func (m *QuerySupplyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySupplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupplyRequest proto.InternalMessageInfo

type QuerySupplyResponse struct {
	CustodiedBTC  uint64 `protobuf:"varint,1,opt,name=custodiedBTC,proto3" json:"custodiedBTC,omitempty"`
	TotalZenBTC   uint64 `protobuf:"varint,2,opt,name=totalZenBTC,proto3" json:"totalZenBTC,omitempty"`
	MintedZenBTC  uint64 `protobuf:"varint,3,opt,name=mintedZenBTC,proto3" json:"mintedZenBTC,omitempty"`
	PendingZenBTC uint64 `protobuf:"varint,4,opt,name=pendingZenBTC,proto3" json:"pendingZenBTC,omitempty"`
	ExchangeRate  string `protobuf:"bytes,5,opt,name=exchangeRate,proto3" json:"exchangeRate,omitempty"`
}

func (m *QuerySupplyResponse) Reset()         { *m = QuerySupplyResponse{} }
func (m *QuerySupplyResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySupplyResponse) ProtoMessage()    {}
func (*QuerySupplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8cea4d05ef3f869, []int{9}
}
func (m *QuerySupplyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySupplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySupplyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySupplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupplyResponse.Merge(m, src)
}
func (m *QuerySupplyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySupplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupplyResponse proto.InternalMessageInfo

func (m *QuerySupplyResponse) GetCustodiedBTC() uint64 {
	if m != nil {
		return m.CustodiedBTC
	}
	return 0
}

func (m *QuerySupplyResponse) GetTotalZenBTC() uint64 {
	if m != nil {
		return m.TotalZenBTC
	}
	return 0
}

func (m *QuerySupplyResponse) GetMintedZenBTC() uint64 {
	if m != nil {
		return m.MintedZenBTC
	}
	return 0
}

func (m *QuerySupplyResponse) GetPendingZenBTC() uint64 {
	if m != nil {
		return m.PendingZenBTC
	}
	return 0
}

func (m *QuerySupplyResponse) GetExchangeRate() string {
	if m != nil {
		return m.ExchangeRate
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "zrchain.zenbtc.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "zrchain.zenbtc.QueryParamsResponse")
	proto.RegisterType((*QueryLockTransactionsRequest)(nil), "zrchain.zenbtc.QueryLockTransactionsRequest")
	proto.RegisterType((*QueryLockTransactionsResponse)(nil), "zrchain.zenbtc.QueryLockTransactionsResponse")
	proto.RegisterType((*QueryRedemptionsRequest)(nil), "zrchain.zenbtc.QueryRedemptionsRequest")
	proto.RegisterType((*QueryRedemptionsResponse)(nil), "zrchain.zenbtc.QueryRedemptionsResponse")
	proto.RegisterType((*QueryPendingMintTransactionsRequest)(nil), "zrchain.zenbtc.QueryPendingMintTransactionsRequest")
	proto.RegisterType((*QueryPendingMintTransactionsResponse)(nil), "zrchain.zenbtc.QueryPendingMintTransactionsResponse")
	proto.RegisterType((*QuerySupplyRequest)(nil), "zrchain.zenbtc.QuerySupplyRequest")
	proto.RegisterType((*QuerySupplyResponse)(nil), "zrchain.zenbtc.QuerySupplyResponse")
}

func init() { proto.RegisterFile("zrchain/zenbtc/query.proto", fileDescriptor_d8cea4d05ef3f869) }

var fileDescriptor_d8cea4d05ef3f869 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcf, 0x4f, 0xd4, 0x4c,
	0x18, 0xde, 0xe1, 0x57, 0xc2, 0xec, 0xf7, 0x6d, 0x60, 0xe0, 0x83, 0xa5, 0xf0, 0x2d, 0x4b, 0x41,
	0x5d, 0x09, 0x6e, 0xc3, 0xe2, 0x41, 0xaf, 0x6b, 0x22, 0x31, 0xc1, 0x04, 0x0b, 0x27, 0x0e, 0x92,
	0x69, 0x77, 0x52, 0x1a, 0xda, 0x99, 0xd2, 0x99, 0x35, 0xc0, 0xc9, 0x78, 0xf4, 0x64, 0xf4, 0x9f,
	0xf0, 0xe8, 0x81, 0x3f, 0x02, 0x6f, 0x24, 0x5e, 0x3c, 0x19, 0x03, 0x26, 0xfe, 0x1b, 0xa6, 0xd3,
	0x29, 0xb4, 0xdd, 0x16, 0xf5, 0xb2, 0x69, 0xde, 0xf7, 0x79, 0x9f, 0xf7, 0x99, 0x77, 0xde, 0x67,
	0x16, 0x6a, 0xa7, 0xa1, 0x7d, 0x80, 0x5d, 0x6a, 0x9c, 0x12, 0x6a, 0x09, 0xdb, 0x38, 0xea, 0x93,
	0xf0, 0xa4, 0x1d, 0x84, 0x4c, 0x30, 0x54, 0x53, 0xb9, 0x76, 0x9c, 0xd3, 0x26, 0xb1, 0xef, 0x52,
	0x66, 0xc8, 0xdf, 0x18, 0xa2, 0xad, 0xda, 0x8c, 0xfb, 0x8c, 0x1b, 0x16, 0xe6, 0x24, 0xae, 0x35,
	0x5e, 0xad, 0x5b, 0x44, 0xe0, 0x75, 0x23, 0xc0, 0x8e, 0x4b, 0xb1, 0x70, 0x19, 0x55, 0xd8, 0x69,
	0x87, 0x39, 0x4c, 0x7e, 0x1a, 0xd1, 0x97, 0x8a, 0x2e, 0x38, 0x8c, 0x39, 0x1e, 0x31, 0x70, 0xe0,
	0x1a, 0x98, 0x52, 0x26, 0x64, 0x09, 0x57, 0xd9, 0xb9, 0x9c, 0x3c, 0xdf, 0xa5, 0x42, 0xa5, 0xe6,
	0x73, 0xa9, 0x00, 0x87, 0xd8, 0x4f, 0xea, 0x9a, 0xb9, 0x64, 0x48, 0x7a, 0xc4, 0x0f, 0x52, 0xcc,
	0xfa, 0x34, 0x44, 0x2f, 0x22, 0xbd, 0xdb, 0xb2, 0xcc, 0x24, 0x47, 0x7d, 0xc2, 0x85, 0xbe, 0x0d,
	0xa7, 0x32, 0x51, 0x1e, 0x30, 0xca, 0x09, 0x7a, 0x0c, 0xc7, 0x62, 0xfa, 0x3a, 0x68, 0x82, 0x56,
	0xb5, 0x33, 0xd3, 0xce, 0x8e, 0xa6, 0x1d, 0xe3, 0xbb, 0xe3, 0xe7, 0xdf, 0x16, 0x2b, 0x1f, 0x7f,
	0x7e, 0x5a, 0x05, 0xa6, 0x2a, 0xd0, 0x1b, 0x70, 0x41, 0x32, 0x6e, 0x31, 0xfb, 0x70, 0x37, 0xc4,
	0x94, 0x63, 0x5b, 0xca, 0x48, 0x3a, 0xfa, 0xf0, 0xff, 0x92, 0xbc, 0xea, 0xbd, 0x05, 0x27, 0x3d,
	0x66, 0x1f, 0xee, 0x8b, 0x54, 0xb2, 0x0e, 0x9a, 0xc3, 0xad, 0x6a, 0x67, 0x31, 0x2f, 0x23, 0x47,
	0x62, 0x4e, 0x78, 0x39, 0x56, 0x5d, 0xc0, 0x59, 0xd9, 0xce, 0xbc, 0x19, 0x88, 0x52, 0x82, 0x16,
	0x61, 0x95, 0x0b, 0x1c, 0x8a, 0x7d, 0x97, 0xf6, 0xc8, 0xb1, 0x3c, 0xe9, 0x88, 0x09, 0x65, 0xe8,
	0x59, 0x14, 0x41, 0x8f, 0xe0, 0x18, 0x17, 0x58, 0xf4, 0x79, 0x7d, 0xa8, 0x09, 0x5a, 0xb5, 0x4e,
	0x33, 0xdf, 0xfe, 0x86, 0x74, 0x47, 0xe2, 0x4c, 0x85, 0xd7, 0x5f, 0xc2, 0xfa, 0x60, 0x57, 0x75,
	0xbe, 0x2e, 0xac, 0xa6, 0x6e, 0x47, 0x9d, 0x4c, 0x2b, 0xa7, 0xee, 0x8e, 0x44, 0x43, 0x36, 0xd3,
	0x45, 0xfa, 0x1d, 0xb8, 0x1c, 0x5f, 0x1b, 0xa1, 0x3d, 0x97, 0x3a, 0xcf, 0x5d, 0x2a, 0x8a, 0x66,
	0xfd, 0x16, 0xc0, 0x95, 0xdb, 0x71, 0x4a, 0x93, 0x05, 0xe7, 0x82, 0x18, 0xb2, 0x1f, 0x6d, 0x5c,
	0xd1, 0xec, 0xef, 0x0e, 0xac, 0x40, 0x21, 0xa7, 0x39, 0x1b, 0x14, 0xf7, 0xba, 0x5e, 0xc0, 0x9d,
	0x7e, 0x10, 0x78, 0x27, 0x89, 0xc4, 0xcf, 0x40, 0x6d, 0x60, 0x12, 0x56, 0x8a, 0x74, 0xf8, 0x8f,
	0xdd, 0xe7, 0x82, 0xf5, 0x5c, 0xd2, 0xeb, 0xee, 0x3e, 0x51, 0xb7, 0x93, 0x89, 0xa1, 0x26, 0xac,
	0x0a, 0x26, 0xb0, 0xb7, 0x47, 0x68, 0x04, 0x19, 0x92, 0x90, 0x74, 0x28, 0x62, 0x89, 0xce, 0x43,
	0x7a, 0x0a, 0x32, 0x1c, 0xb3, 0xa4, 0x63, 0x68, 0x05, 0xfe, 0xab, 0x24, 0x2b, 0xd0, 0x88, 0x04,
	0x65, 0x83, 0x11, 0x13, 0x39, 0xb6, 0x0f, 0x30, 0x75, 0x88, 0x89, 0x05, 0xa9, 0x8f, 0x36, 0x41,
	0x6b, 0xdc, 0xcc, 0xc4, 0x3a, 0x67, 0xa3, 0x70, 0x54, 0x9e, 0x05, 0x79, 0x70, 0x7c, 0x93, 0x88,
	0xd8, 0x24, 0x48, 0xcf, 0x4f, 0x6e, 0xd0, 0x87, 0xda, 0xf2, 0xad, 0x98, 0x78, 0x26, 0xfa, 0xcc,
	0x9b, 0x2f, 0x3f, 0x3e, 0x0c, 0x4d, 0xa0, 0x5a, 0xf6, 0x09, 0x40, 0xef, 0x01, 0x9c, 0xc8, 0xdb,
	0x09, 0xad, 0x15, 0x32, 0x96, 0xb8, 0x52, 0x7b, 0xf0, 0x87, 0x68, 0xa5, 0x64, 0x49, 0x2a, 0x99,
	0x47, 0x73, 0x89, 0x92, 0x01, 0xc7, 0xa2, 0xd7, 0x00, 0xd6, 0x36, 0x89, 0x48, 0x39, 0x00, 0xdd,
	0x2b, 0x6c, 0x32, 0xe8, 0x4c, 0xad, 0xf5, 0x7b, 0xa0, 0x12, 0x32, 0x2f, 0x85, 0xfc, 0x87, 0xa6,
	0x0a, 0x1e, 0x3e, 0x74, 0x06, 0xd4, 0x5b, 0x54, 0xb2, 0xfe, 0x68, 0xa3, 0x78, 0xea, 0xb7, 0x9a,
	0x4a, 0x7b, 0xf8, 0x77, 0x45, 0x4a, 0xe8, 0x7d, 0x29, 0x74, 0x19, 0x2d, 0x5d, 0xdf, 0x5d, 0x99,
	0xdf, 0x10, 0x85, 0xd5, 0x94, 0x23, 0x4a, 0xd6, 0x27, 0xe3, 0xa2, 0x92, 0xf5, 0xc9, 0x5a, 0x6a,
	0x70, 0x7d, 0xb8, 0xcc, 0x77, 0x9f, 0x9e, 0x5f, 0x36, 0xc0, 0xc5, 0x65, 0x03, 0x7c, 0xbf, 0x6c,
	0x80, 0x77, 0x57, 0x8d, 0xca, 0xc5, 0x55, 0xa3, 0xf2, 0xf5, 0xaa, 0x51, 0xd9, 0x5b, 0x73, 0x5c,
	0x71, 0xd0, 0xb7, 0xda, 0x36, 0xf3, 0xa3, 0x9a, 0x90, 0xd9, 0x87, 0x1e, 0xb6, 0x78, 0x52, 0x7f,
	0x9c, 0x7c, 0x88, 0x93, 0x80, 0x70, 0x6b, 0x4c, 0xfe, 0xd1, 0x6c, 0xfc, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x2c, 0xfd, 0x51, 0xb2, 0x63, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	GetParams(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of LockTransactions items.
	LockTransactions(ctx context.Context, in *QueryLockTransactionsRequest, opts ...grpc.CallOption) (*QueryLockTransactionsResponse, error)
	// Queries a list of Redemptions items.
	GetRedemptions(ctx context.Context, in *QueryRedemptionsRequest, opts ...grpc.CallOption) (*QueryRedemptionsResponse, error)
	// Queries a list of PendingMintTransactions items.
	QueryPendingMintTransactions(ctx context.Context, in *QueryPendingMintTransactionsRequest, opts ...grpc.CallOption) (*QueryPendingMintTransactionsResponse, error)
	// Queries the current supply of zenBTC.
	QuerySupply(ctx context.Context, in *QuerySupplyRequest, opts ...grpc.CallOption) (*QuerySupplyResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetParams(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/zrchain.zenbtc.Query/GetParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LockTransactions(ctx context.Context, in *QueryLockTransactionsRequest, opts ...grpc.CallOption) (*QueryLockTransactionsResponse, error) {
	out := new(QueryLockTransactionsResponse)
	err := c.cc.Invoke(ctx, "/zrchain.zenbtc.Query/LockTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRedemptions(ctx context.Context, in *QueryRedemptionsRequest, opts ...grpc.CallOption) (*QueryRedemptionsResponse, error) {
	out := new(QueryRedemptionsResponse)
	err := c.cc.Invoke(ctx, "/zrchain.zenbtc.Query/GetRedemptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryPendingMintTransactions(ctx context.Context, in *QueryPendingMintTransactionsRequest, opts ...grpc.CallOption) (*QueryPendingMintTransactionsResponse, error) {
	out := new(QueryPendingMintTransactionsResponse)
	err := c.cc.Invoke(ctx, "/zrchain.zenbtc.Query/QueryPendingMintTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QuerySupply(ctx context.Context, in *QuerySupplyRequest, opts ...grpc.CallOption) (*QuerySupplyResponse, error) {
	out := new(QuerySupplyResponse)
	err := c.cc.Invoke(ctx, "/zrchain.zenbtc.Query/QuerySupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	GetParams(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of LockTransactions items.
	LockTransactions(context.Context, *QueryLockTransactionsRequest) (*QueryLockTransactionsResponse, error)
	// Queries a list of Redemptions items.
	GetRedemptions(context.Context, *QueryRedemptionsRequest) (*QueryRedemptionsResponse, error)
	// Queries a list of PendingMintTransactions items.
	QueryPendingMintTransactions(context.Context, *QueryPendingMintTransactionsRequest) (*QueryPendingMintTransactionsResponse, error)
	// Queries the current supply of zenBTC.
	QuerySupply(context.Context, *QuerySupplyRequest) (*QuerySupplyResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetParams(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParams not implemented")
}
func (*UnimplementedQueryServer) LockTransactions(ctx context.Context, req *QueryLockTransactionsRequest) (*QueryLockTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockTransactions not implemented")
}
func (*UnimplementedQueryServer) GetRedemptions(ctx context.Context, req *QueryRedemptionsRequest) (*QueryRedemptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedemptions not implemented")
}
func (*UnimplementedQueryServer) QueryPendingMintTransactions(ctx context.Context, req *QueryPendingMintTransactionsRequest) (*QueryPendingMintTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPendingMintTransactions not implemented")
}
func (*UnimplementedQueryServer) QuerySupply(ctx context.Context, req *QuerySupplyRequest) (*QuerySupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySupply not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zrchain.zenbtc.Query/GetParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParams(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LockTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLockTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LockTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zrchain.zenbtc.Query/LockTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LockTransactions(ctx, req.(*QueryLockTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRedemptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRedemptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRedemptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zrchain.zenbtc.Query/GetRedemptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRedemptions(ctx, req.(*QueryRedemptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryPendingMintTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingMintTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryPendingMintTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zrchain.zenbtc.Query/QueryPendingMintTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryPendingMintTransactions(ctx, req.(*QueryPendingMintTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QuerySupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySupplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QuerySupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zrchain.zenbtc.Query/QuerySupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QuerySupply(ctx, req.(*QuerySupplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zrchain.zenbtc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParams",
			Handler:    _Query_GetParams_Handler,
		},
		{
			MethodName: "LockTransactions",
			Handler:    _Query_LockTransactions_Handler,
		},
		{
			MethodName: "GetRedemptions",
			Handler:    _Query_GetRedemptions_Handler,
		},
		{
			MethodName: "QueryPendingMintTransactions",
			Handler:    _Query_QueryPendingMintTransactions_Handler,
		},
		{
			MethodName: "QuerySupply",
			Handler:    _Query_QuerySupply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zrchain/zenbtc/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLockTransactionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockTransactionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockTransactionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLockTransactionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockTransactionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockTransactionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LockTransactions) > 0 {
		for iNdEx := len(m.LockTransactions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LockTransactions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRedemptionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRedemptionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRedemptionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if m.StartIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRedemptionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRedemptionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRedemptionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Redemptions) > 0 {
		for iNdEx := len(m.Redemptions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Redemptions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPendingMintTransactionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingMintTransactionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingMintTransactionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPendingMintTransactionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingMintTransactionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingMintTransactionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PendingMintTransactions) > 0 {
		for iNdEx := len(m.PendingMintTransactions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingMintTransactions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QuerySupplyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySupplyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySupplyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySupplyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySupplyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySupplyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExchangeRate) > 0 {
		i -= len(m.ExchangeRate)
		copy(dAtA[i:], m.ExchangeRate)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ExchangeRate)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PendingZenBTC != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PendingZenBTC))
		i--
		dAtA[i] = 0x20
	}
	if m.MintedZenBTC != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MintedZenBTC))
		i--
		dAtA[i] = 0x18
	}
	if m.TotalZenBTC != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalZenBTC))
		i--
		dAtA[i] = 0x10
	}
	if m.CustodiedBTC != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CustodiedBTC))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLockTransactionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLockTransactionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LockTransactions) > 0 {
		for _, e := range m.LockTransactions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryRedemptionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartIndex != 0 {
		n += 1 + sovQuery(uint64(m.StartIndex))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	return n
}

func (m *QueryRedemptionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Redemptions) > 0 {
		for _, e := range m.Redemptions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryPendingMintTransactionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPendingMintTransactionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PendingMintTransactions) > 0 {
		for _, e := range m.PendingMintTransactions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QuerySupplyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySupplyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustodiedBTC != 0 {
		n += 1 + sovQuery(uint64(m.CustodiedBTC))
	}
	if m.TotalZenBTC != 0 {
		n += 1 + sovQuery(uint64(m.TotalZenBTC))
	}
	if m.MintedZenBTC != 0 {
		n += 1 + sovQuery(uint64(m.MintedZenBTC))
	}
	if m.PendingZenBTC != 0 {
		n += 1 + sovQuery(uint64(m.PendingZenBTC))
	}
	l = len(m.ExchangeRate)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockTransactionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockTransactionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockTransactionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockTransactionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockTransactionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockTransactionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockTransactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockTransactions = append(m.LockTransactions, &LockTransaction{})
			if err := m.LockTransactions[len(m.LockTransactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRedemptionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRedemptionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRedemptionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartIndex", wireType)
			}
			m.StartIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RedemptionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRedemptionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRedemptionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRedemptionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Redemptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Redemptions = append(m.Redemptions, Redemption{})
			if err := m.Redemptions[len(m.Redemptions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingMintTransactionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingMintTransactionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingMintTransactionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingMintTransactionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingMintTransactionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingMintTransactionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingMintTransactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingMintTransactions = append(m.PendingMintTransactions, &PendingMintTransaction{})
			if err := m.PendingMintTransactions[len(m.PendingMintTransactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySupplyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySupplyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySupplyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySupplyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySupplyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySupplyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustodiedBTC", wireType)
			}
			m.CustodiedBTC = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CustodiedBTC |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalZenBTC", wireType)
			}
			m.TotalZenBTC = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalZenBTC |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedZenBTC", wireType)
			}
			m.MintedZenBTC = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintedZenBTC |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingZenBTC", wireType)
			}
			m.PendingZenBTC = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingZenBTC |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExchangeRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
