// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zrchain/zenbtc/redemptions.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Redemption contains the data for a redemption transaction.
type Redemption struct {
	Data      RedemptionData `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`
	Completed bool           `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (m *Redemption) Reset()         { *m = Redemption{} }
func (m *Redemption) String() string { return proto.CompactTextString(m) }
func (*Redemption) ProtoMessage()    {}
func (*Redemption) Descriptor() ([]byte, []int) {
	return fileDescriptor_c558a292253a42cf, []int{0}
}
func (m *Redemption) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Redemption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Redemption.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Redemption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redemption.Merge(m, src)
}
func (m *Redemption) XXX_Size() int {
	return m.Size()
}
func (m *Redemption) XXX_DiscardUnknown() {
	xxx_messageInfo_Redemption.DiscardUnknown(m)
}

var xxx_messageInfo_Redemption proto.InternalMessageInfo

func (m *Redemption) GetData() RedemptionData {
	if m != nil {
		return m.Data
	}
	return RedemptionData{}
}

func (m *Redemption) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type RedemptionData struct {
	Id                 uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DestinationAddress []byte `protobuf:"bytes,2,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	Amount             uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *RedemptionData) Reset()         { *m = RedemptionData{} }
func (m *RedemptionData) String() string { return proto.CompactTextString(m) }
func (*RedemptionData) ProtoMessage()    {}
func (*RedemptionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c558a292253a42cf, []int{1}
}
func (m *RedemptionData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RedemptionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RedemptionData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RedemptionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedemptionData.Merge(m, src)
}
func (m *RedemptionData) XXX_Size() int {
	return m.Size()
}
func (m *RedemptionData) XXX_DiscardUnknown() {
	xxx_messageInfo_RedemptionData.DiscardUnknown(m)
}

var xxx_messageInfo_RedemptionData proto.InternalMessageInfo

func (m *RedemptionData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RedemptionData) GetDestinationAddress() []byte {
	if m != nil {
		return m.DestinationAddress
	}
	return nil
}

func (m *RedemptionData) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Redemption)(nil), "zrchain.zenbtc.Redemption")
	proto.RegisterType((*RedemptionData)(nil), "zrchain.zenbtc.RedemptionData")
}

func init() { proto.RegisterFile("zrchain/zenbtc/redemptions.proto", fileDescriptor_c558a292253a42cf) }

var fileDescriptor_c558a292253a42cf = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0x9b, 0x59, 0x86, 0x46, 0xe9, 0x21, 0x8a, 0x14, 0x91, 0x58, 0x76, 0xda, 0x41, 0x5a,
	0xd0, 0x8b, 0x57, 0x87, 0xf8, 0x01, 0x72, 0xf4, 0x22, 0x69, 0x12, 0xba, 0xe0, 0x9a, 0x94, 0xe4,
	0x3f, 0xd0, 0x7d, 0x0a, 0x3f, 0xd6, 0x8e, 0x3b, 0x7a, 0x12, 0x69, 0xbf, 0x88, 0x34, 0xdd, 0x9c,
	0xbb, 0xbd, 0xe4, 0xfd, 0xde, 0xfb, 0xc3, 0xc3, 0xd9, 0xca, 0x89, 0x39, 0xd7, 0xa6, 0x58, 0x29,
	0x53, 0x82, 0x28, 0x9c, 0x92, 0xaa, 0x6e, 0x40, 0x5b, 0xe3, 0xf3, 0xc6, 0x59, 0xb0, 0x24, 0xd9,
	0x12, 0xf9, 0x40, 0x5c, 0x5d, 0x54, 0xb6, 0xb2, 0xc1, 0x2a, 0x7a, 0x35, 0x50, 0x13, 0x89, 0x31,
	0xfb, 0x8b, 0x92, 0x07, 0x1c, 0x4b, 0x0e, 0x3c, 0x45, 0x19, 0x9a, 0x9e, 0xde, 0xd1, 0xfc, 0xb0,
	0x22, 0xdf, 0x93, 0x4f, 0x1c, 0xf8, 0x2c, 0x5e, 0x7f, 0xdf, 0x44, 0x2c, 0x24, 0xc8, 0x35, 0x3e,
	0x11, 0xb6, 0x6e, 0x16, 0x0a, 0x94, 0x4c, 0x47, 0x19, 0x9a, 0x1e, 0xb3, 0xfd, 0xc7, 0x44, 0xe3,
	0xe4, 0x30, 0x4b, 0x12, 0x3c, 0xd2, 0x32, 0xdc, 0x89, 0xd9, 0x48, 0x4b, 0x52, 0xe0, 0x73, 0xa9,
	0x3c, 0x68, 0xc3, 0x7b, 0xe4, 0x95, 0x4b, 0xe9, 0x94, 0xf7, 0xa1, 0xe9, 0x8c, 0x91, 0x7f, 0xd6,
	0xe3, 0xe0, 0x90, 0x4b, 0x3c, 0xe6, 0xb5, 0x5d, 0x1a, 0x48, 0x8f, 0x42, 0xc9, 0xf6, 0x35, 0x7b,
	0x5e, 0xb7, 0x14, 0x6d, 0x5a, 0x8a, 0x7e, 0x5a, 0x8a, 0x3e, 0x3b, 0x1a, 0x6d, 0x3a, 0x1a, 0x7d,
	0x75, 0x34, 0x7a, 0xb9, 0xad, 0x34, 0xcc, 0x97, 0x65, 0x2e, 0x6c, 0xdd, 0xaf, 0xe6, 0xac, 0x78,
	0x5b, 0xf0, 0xd2, 0xef, 0x16, 0x7c, 0xdf, 0x09, 0xf8, 0x68, 0x94, 0x2f, 0xc7, 0x61, 0x9f, 0xfb,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x22, 0x35, 0xce, 0x69, 0x01, 0x00, 0x00,
}

func (m *Redemption) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Redemption) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Redemption) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Completed {
		i--
		if m.Completed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRedemptions(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RedemptionData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedemptionData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedemptionData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintRedemptions(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DestinationAddress) > 0 {
		i -= len(m.DestinationAddress)
		copy(dAtA[i:], m.DestinationAddress)
		i = encodeVarintRedemptions(dAtA, i, uint64(len(m.DestinationAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintRedemptions(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRedemptions(dAtA []byte, offset int, v uint64) int {
	offset -= sovRedemptions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Redemption) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Data.Size()
	n += 1 + l + sovRedemptions(uint64(l))
	if m.Completed {
		n += 2
	}
	return n
}

func (m *RedemptionData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovRedemptions(uint64(m.Id))
	}
	l = len(m.DestinationAddress)
	if l > 0 {
		n += 1 + l + sovRedemptions(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovRedemptions(uint64(m.Amount))
	}
	return n
}

func sovRedemptions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRedemptions(x uint64) (n int) {
	return sovRedemptions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Redemption) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRedemptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Redemption: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Redemption: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedemptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRedemptions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRedemptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Completed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedemptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Completed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipRedemptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRedemptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RedemptionData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRedemptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedemptionData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedemptionData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedemptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedemptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRedemptions
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRedemptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationAddress = append(m.DestinationAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.DestinationAddress == nil {
				m.DestinationAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedemptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRedemptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRedemptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRedemptions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRedemptions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRedemptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRedemptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRedemptions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRedemptions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRedemptions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRedemptions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRedemptions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRedemptions = fmt.Errorf("proto: unexpected end of group")
)
